[package]
name = "system-timer"
version = "0.1.0"
edition = "2021"
authors = ["Stephan <kiffie@mailbox.org>"]
license = "GPL-2.0-or-later"

[features]
pic32mx1xxfxxxb = ["pic32-hal/pic32mx1xxfxxxb", "pic32"]
pic32mx2xxfxxxb = ["pic32-hal/pic32mx2xxfxxxb", "pic32"]
pic32mx2x4fxxxb = ["pic32-hal/pic32mx2x4fxxxb", "pic32"]
std = ["device-selected"]
pic32mx47x = ["pic32-hal/pic32mx47x", "pic32"]
rp2040 = ["rp2040-hal", "cortex-m", "device-selected"]
pic32 = ["mips-mcu", "device-selected", "konst"]
embedded_hal_02 = ["dep:embedded_hal_02"]
device-selected = []
#default = ["pic32mx47x", "embedded_hal_02"]
#default = ["rp2040"]
#default = ["std"]

[dependencies]
pic32-hal = { version = "0.13.0", optional = true }
mips-mcu = { version = "0.3.0", optional = true }
critical-section = "1.2.0"
log = "0.4.22"
konst = { version = "0.3.9", optional = true }
rp2040-hal = { version = "0.11.0", features = ["rt"], optional = true }
cortex-m = { version = "0.7.7", optional = true }
nb = "1.1.0"
void = { version = "1.0.0", default-features = false }
fugit = "0.3.7"
cfg-if = "1.0.0"
embedded_hal_02 = { package = "embedded-hal", version = "0.2.7", features=["unproven"], optional = true }
